// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resources.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Required information from client for every request
type ClientMeta struct {
	// k8s "namespace" the client wants to operate _for_
	// nb: we're not actually interacting with k8s here
	// we use tags on AWS resources to control which k8s namespace secrets are _for_
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientMeta) Reset()         { *m = ClientMeta{} }
func (m *ClientMeta) String() string { return proto.CompactTextString(m) }
func (*ClientMeta) ProtoMessage()    {}
func (*ClientMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf1b13971fe4c19d, []int{0}
}

func (m *ClientMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMeta.Unmarshal(m, b)
}
func (m *ClientMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMeta.Marshal(b, m, deterministic)
}
func (m *ClientMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMeta.Merge(m, src)
}
func (m *ClientMeta) XXX_Size() int {
	return xxx_messageInfo_ClientMeta.Size(m)
}
func (m *ClientMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMeta proto.InternalMessageInfo

func (m *ClientMeta) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type PingRequest struct {
	Metadata             *ClientMeta `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf1b13971fe4c19d, []int{1}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetMetadata() *ClientMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type PingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf1b13971fe4c19d, []int{2}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

type CreateSecretRequest struct {
	Metadata             *ClientMeta `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value                string      `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateSecretRequest) Reset()         { *m = CreateSecretRequest{} }
func (m *CreateSecretRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSecretRequest) ProtoMessage()    {}
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf1b13971fe4c19d, []int{3}
}

func (m *CreateSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSecretRequest.Unmarshal(m, b)
}
func (m *CreateSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSecretRequest.Marshal(b, m, deterministic)
}
func (m *CreateSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSecretRequest.Merge(m, src)
}
func (m *CreateSecretRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSecretRequest.Size(m)
}
func (m *CreateSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSecretRequest proto.InternalMessageInfo

func (m *CreateSecretRequest) GetMetadata() *ClientMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CreateSecretRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateSecretRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CreateSecretResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSecretResponse) Reset()         { *m = CreateSecretResponse{} }
func (m *CreateSecretResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSecretResponse) ProtoMessage()    {}
func (*CreateSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf1b13971fe4c19d, []int{4}
}

func (m *CreateSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSecretResponse.Unmarshal(m, b)
}
func (m *CreateSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSecretResponse.Marshal(b, m, deterministic)
}
func (m *CreateSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSecretResponse.Merge(m, src)
}
func (m *CreateSecretResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSecretResponse.Size(m)
}
func (m *CreateSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSecretResponse proto.InternalMessageInfo

type ListSecretsRequest struct {
	Metadata             *ClientMeta `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListSecretsRequest) Reset()         { *m = ListSecretsRequest{} }
func (m *ListSecretsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSecretsRequest) ProtoMessage()    {}
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf1b13971fe4c19d, []int{5}
}

func (m *ListSecretsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSecretsRequest.Unmarshal(m, b)
}
func (m *ListSecretsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSecretsRequest.Marshal(b, m, deterministic)
}
func (m *ListSecretsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSecretsRequest.Merge(m, src)
}
func (m *ListSecretsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSecretsRequest.Size(m)
}
func (m *ListSecretsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSecretsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSecretsRequest proto.InternalMessageInfo

func (m *ListSecretsRequest) GetMetadata() *ClientMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ListSecretsResponse struct {
	Secrets              []string `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSecretsResponse) Reset()         { *m = ListSecretsResponse{} }
func (m *ListSecretsResponse) String() string { return proto.CompactTextString(m) }
func (*ListSecretsResponse) ProtoMessage()    {}
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf1b13971fe4c19d, []int{6}
}

func (m *ListSecretsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSecretsResponse.Unmarshal(m, b)
}
func (m *ListSecretsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSecretsResponse.Marshal(b, m, deterministic)
}
func (m *ListSecretsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSecretsResponse.Merge(m, src)
}
func (m *ListSecretsResponse) XXX_Size() int {
	return xxx_messageInfo_ListSecretsResponse.Size(m)
}
func (m *ListSecretsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSecretsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSecretsResponse proto.InternalMessageInfo

func (m *ListSecretsResponse) GetSecrets() []string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

type BindSecretRequest struct {
	Metadata             *ClientMeta `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ServiceAccountName   string      `protobuf:"bytes,3,opt,name=serviceAccountName,proto3" json:"serviceAccountName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BindSecretRequest) Reset()         { *m = BindSecretRequest{} }
func (m *BindSecretRequest) String() string { return proto.CompactTextString(m) }
func (*BindSecretRequest) ProtoMessage()    {}
func (*BindSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf1b13971fe4c19d, []int{7}
}

func (m *BindSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindSecretRequest.Unmarshal(m, b)
}
func (m *BindSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindSecretRequest.Marshal(b, m, deterministic)
}
func (m *BindSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindSecretRequest.Merge(m, src)
}
func (m *BindSecretRequest) XXX_Size() int {
	return xxx_messageInfo_BindSecretRequest.Size(m)
}
func (m *BindSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BindSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BindSecretRequest proto.InternalMessageInfo

func (m *BindSecretRequest) GetMetadata() *ClientMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *BindSecretRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BindSecretRequest) GetServiceAccountName() string {
	if m != nil {
		return m.ServiceAccountName
	}
	return ""
}

type BindSecretResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindSecretResponse) Reset()         { *m = BindSecretResponse{} }
func (m *BindSecretResponse) String() string { return proto.CompactTextString(m) }
func (*BindSecretResponse) ProtoMessage()    {}
func (*BindSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf1b13971fe4c19d, []int{8}
}

func (m *BindSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindSecretResponse.Unmarshal(m, b)
}
func (m *BindSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindSecretResponse.Marshal(b, m, deterministic)
}
func (m *BindSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindSecretResponse.Merge(m, src)
}
func (m *BindSecretResponse) XXX_Size() int {
	return xxx_messageInfo_BindSecretResponse.Size(m)
}
func (m *BindSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BindSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BindSecretResponse proto.InternalMessageInfo

type CreateSecretIAMPolicyRequest struct {
	Metadata             *ClientMeta `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateSecretIAMPolicyRequest) Reset()         { *m = CreateSecretIAMPolicyRequest{} }
func (m *CreateSecretIAMPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSecretIAMPolicyRequest) ProtoMessage()    {}
func (*CreateSecretIAMPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf1b13971fe4c19d, []int{9}
}

func (m *CreateSecretIAMPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSecretIAMPolicyRequest.Unmarshal(m, b)
}
func (m *CreateSecretIAMPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSecretIAMPolicyRequest.Marshal(b, m, deterministic)
}
func (m *CreateSecretIAMPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSecretIAMPolicyRequest.Merge(m, src)
}
func (m *CreateSecretIAMPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSecretIAMPolicyRequest.Size(m)
}
func (m *CreateSecretIAMPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSecretIAMPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSecretIAMPolicyRequest proto.InternalMessageInfo

func (m *CreateSecretIAMPolicyRequest) GetMetadata() *ClientMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CreateSecretIAMPolicyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateSecretIAMPolicyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSecretIAMPolicyResponse) Reset()         { *m = CreateSecretIAMPolicyResponse{} }
func (m *CreateSecretIAMPolicyResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSecretIAMPolicyResponse) ProtoMessage()    {}
func (*CreateSecretIAMPolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf1b13971fe4c19d, []int{10}
}

func (m *CreateSecretIAMPolicyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSecretIAMPolicyResponse.Unmarshal(m, b)
}
func (m *CreateSecretIAMPolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSecretIAMPolicyResponse.Marshal(b, m, deterministic)
}
func (m *CreateSecretIAMPolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSecretIAMPolicyResponse.Merge(m, src)
}
func (m *CreateSecretIAMPolicyResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSecretIAMPolicyResponse.Size(m)
}
func (m *CreateSecretIAMPolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSecretIAMPolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSecretIAMPolicyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClientMeta)(nil), "kiss.resources.ClientMeta")
	proto.RegisterType((*PingRequest)(nil), "kiss.resources.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "kiss.resources.PingResponse")
	proto.RegisterType((*CreateSecretRequest)(nil), "kiss.resources.CreateSecretRequest")
	proto.RegisterType((*CreateSecretResponse)(nil), "kiss.resources.CreateSecretResponse")
	proto.RegisterType((*ListSecretsRequest)(nil), "kiss.resources.ListSecretsRequest")
	proto.RegisterType((*ListSecretsResponse)(nil), "kiss.resources.ListSecretsResponse")
	proto.RegisterType((*BindSecretRequest)(nil), "kiss.resources.BindSecretRequest")
	proto.RegisterType((*BindSecretResponse)(nil), "kiss.resources.BindSecretResponse")
	proto.RegisterType((*CreateSecretIAMPolicyRequest)(nil), "kiss.resources.CreateSecretIAMPolicyRequest")
	proto.RegisterType((*CreateSecretIAMPolicyResponse)(nil), "kiss.resources.CreateSecretIAMPolicyResponse")
}

func init() { proto.RegisterFile("resources.proto", fileDescriptor_cf1b13971fe4c19d) }

var fileDescriptor_cf1b13971fe4c19d = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x35, 0xb6, 0x7e, 0xf4, 0x76, 0x59, 0xf1, 0x6e, 0x95, 0x10, 0xbb, 0xec, 0x3a, 0xeb, 0xc3,
	0x22, 0x9a, 0xc0, 0x0a, 0xbe, 0xef, 0x16, 0x1f, 0x16, 0x5b, 0x29, 0x29, 0x82, 0xe8, 0xd3, 0x74,
	0x7a, 0x69, 0x47, 0xdb, 0x4c, 0xcd, 0x4c, 0x22, 0xfe, 0x0a, 0x7f, 0x9b, 0xff, 0x48, 0x92, 0xb4,
	0x69, 0x9a, 0xd4, 0xb0, 0x50, 0xfa, 0x94, 0xcc, 0x9d, 0x33, 0xe7, 0x9c, 0x39, 0x39, 0x04, 0x9e,
	0x84, 0xa4, 0x55, 0x14, 0x0a, 0xd2, 0xee, 0x32, 0x54, 0x46, 0xe1, 0xf1, 0x0f, 0xa9, 0xb5, 0x9b,
	0x4f, 0xd9, 0x6b, 0x80, 0xde, 0x5c, 0x52, 0x60, 0x06, 0x64, 0x38, 0x76, 0xa1, 0x15, 0xf0, 0x05,
	0xe9, 0x25, 0x17, 0x64, 0x5b, 0xe7, 0xd6, 0x65, 0xcb, 0xdf, 0x0c, 0xd8, 0x07, 0x68, 0x0f, 0x65,
	0x30, 0xf5, 0xe9, 0x67, 0x44, 0xda, 0xe0, 0x7b, 0x78, 0xbc, 0x20, 0xc3, 0x27, 0xdc, 0xf0, 0x14,
	0xdb, 0xbe, 0x72, 0xdc, 0x6d, 0x76, 0x77, 0x43, 0xed, 0xe7, 0x58, 0x76, 0x0c, 0x47, 0x19, 0x8d,
	0x5e, 0xaa, 0x40, 0x13, 0xfb, 0x05, 0x27, 0xbd, 0x90, 0xb8, 0xa1, 0x11, 0x89, 0x90, 0xcc, 0x9e,
	0xf4, 0x88, 0xd0, 0x4c, 0x2c, 0xdb, 0xf7, 0x53, 0xfb, 0xe9, 0x3b, 0x76, 0xe0, 0x41, 0xcc, 0xe7,
	0x11, 0xd9, 0x8d, 0x74, 0x98, 0x2d, 0xd8, 0x73, 0xe8, 0x6c, 0x0b, 0xaf, 0x0c, 0xf5, 0x01, 0xfb,
	0x52, 0x9b, 0x6c, 0xaa, 0xf7, 0xbd, 0xae, 0x07, 0x27, 0x5b, 0x6c, 0x99, 0x08, 0xda, 0xf0, 0x48,
	0x67, 0x23, 0xdb, 0x3a, 0x6f, 0x5c, 0xb6, 0xfc, 0xf5, 0x92, 0xfd, 0xb1, 0xe0, 0xe9, 0x8d, 0x0c,
	0x26, 0x87, 0x8b, 0xc3, 0x05, 0xd4, 0x14, 0xc6, 0x52, 0xd0, 0xb5, 0x10, 0x2a, 0x0a, 0xcc, 0xa7,
	0x04, 0x91, 0x65, 0xb3, 0x63, 0x87, 0x75, 0x00, 0x8b, 0x86, 0x56, 0x31, 0x7d, 0x87, 0x6e, 0x31,
	0xbe, 0xdb, 0xeb, 0xc1, 0x50, 0xcd, 0xa5, 0xf8, 0x7d, 0x00, 0xc7, 0xec, 0x0c, 0x4e, 0xff, 0xa3,
	0x95, 0x99, 0xb9, 0xfa, 0xdb, 0x80, 0xe6, 0xc7, 0xdb, 0xd1, 0x08, 0x7b, 0xd0, 0x4c, 0xda, 0x85,
	0x2f, 0xca, 0x5a, 0x85, 0xea, 0x3a, 0xdd, 0xdd, 0x9b, 0xab, 0x8b, 0xdd, 0xc3, 0x6f, 0x70, 0x54,
	0x94, 0xc3, 0x8b, 0x8a, 0xf1, 0x6a, 0x61, 0x9d, 0x57, 0xf5, 0xa0, 0x9c, 0xfc, 0x0b, 0xb4, 0x0b,
	0x85, 0x40, 0x56, 0x3e, 0x56, 0xed, 0x9e, 0x73, 0x51, 0x8b, 0xc9, 0x99, 0x3f, 0x03, 0x6c, 0xbe,
	0x13, 0xbe, 0x2c, 0x1f, 0xaa, 0x94, 0xca, 0x61, 0x75, 0x90, 0x9c, 0x36, 0x86, 0x67, 0x3b, 0xc3,
	0xc7, 0x37, 0x75, 0x37, 0x2e, 0xf7, 0xc1, 0x79, 0x7b, 0x47, 0xf4, 0x5a, 0xf7, 0xe6, 0xec, 0xeb,
	0xe9, 0x54, 0x9a, 0x59, 0x34, 0x76, 0x85, 0x5a, 0x78, 0x2a, 0x56, 0x86, 0xc4, 0xcc, 0x4b, 0x48,
	0xbc, 0xf4, 0x67, 0x36, 0x7e, 0x98, 0x3e, 0xde, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x04,
	0xaf, 0x1f, 0xe6, 0x04, 0x00, 0x00,
}
